export type MekLocBillingChoice = 'six_months' | 'annual' | 'lifetime';

export const MEKLOC_ALL_FEATURES = [
  'Réservations et calendrier',
  'Gestion des clients et documents',
  'Gestion complète des véhicules',
  'Contrats PDF personnalisés',
  'Paiements, cautions et restes à payer',
  'Entretien et échéances véhicules',
  'Rapports et statistiques',
  'Alertes et rappels',
  'Accès équipe et rôles',
  'Support prioritaire',
] as const;

export const MEKLOC_PLANS = {
  starter: {
    id: 'starter',
    name: 'Starter',
    monthlyPrice: 399,
    annualPrice: 2394,
    billingTotal: 2394,
    lifetimePrice: 0,
    billingChoice: 'six_months',
    monthlyLabel: '399 MAD / mois',
    annualLabel: '2 394 MAD / 6 mois',
    annualBillingLabel: 'Facturé 2 394 MAD / 6 mois',
    billingLabel: 'Facturé 2 394 MAD / 6 mois',
    commitment: 'Engagement 6 mois',
    usersLabel: '1 utilisateur',
    vehiclesLabel: 'Jusqu’à 15 véhicules',
    note: 'L’essentiel pour démarrer avec une flotte compacte.',
    badge: '',
    features: ['Réservations & calendrier', 'Gestion clients', 'Gestion véhicules', 'Contrats PDF', 'Paiements & cautions', 'Support standard'],
  },
  pro: {
    id: 'pro',
    name: 'Pro',
    monthlyPrice: 299,
    annualPrice: 3588,
    billingTotal: 3588,
    lifetimePrice: 0,
    billingChoice: 'annual',
    monthlyLabel: '299 MAD / mois',
    annualLabel: '3 588 MAD / an',
    annualBillingLabel: 'Facturé 3 588 MAD / an',
    billingLabel: 'Facturé 3 588 MAD / an',
    commitment: 'Engagement 12 mois',
    usersLabel: '3 utilisateurs',
    vehiclesLabel: 'Jusqu’à 50 véhicules',
    note: 'Le meilleur équilibre pour les agences en croissance.',
    badge: 'Le plus choisi',
    features: ['Tout de Starter', 'Rapports financiers', 'Alertes & rappels', 'Entretien & échéances', 'Documents clients', 'Support prioritaire'],
  },
  business: {
    id: 'business',
    name: 'Business',
    monthlyPrice: 499,
    annualPrice: 5988,
    billingTotal: 5988,
    lifetimePrice: 0,
    billingChoice: 'annual',
    monthlyLabel: '499 MAD / mois',
    annualLabel: '5 988 MAD / an',
    annualBillingLabel: 'Facturé 5 988 MAD / an',
    billingLabel: 'Facturé 5 988 MAD / an',
    commitment: 'Engagement 12 mois',
    usersLabel: 'Utilisateurs illimités',
    vehiclesLabel: 'Véhicules illimités',
    note: 'Une gestion complète pour les équipes et grandes flottes.',
    badge: '',
    features: ['Tout de Pro', 'Multi-utilisateurs', 'Sessions & sécurité', 'Accompagnement personnalisé', 'Gestion avancée agence', 'Support premium'],
  },
  lifetime: {
    id: 'lifetime',
    name: 'Lifetime',
    monthlyPrice: 0,
    annualPrice: 9999,
    billingTotal: 9999,
    lifetimePrice: 9999,
    billingChoice: 'lifetime',
    monthlyLabel: '9 999 MAD',
    annualLabel: '9 999 MAD',
    annualBillingLabel: 'Paiement unique',
    billingLabel: 'Paiement unique',
    commitment: 'Accès à vie',
    usersLabel: 'Utilisateurs illimités',
    vehiclesLabel: 'Véhicules illimités',
    note: 'Toutes les fonctionnalités avec un paiement unique.',
    badge: 'Offre limitée',
    features: ['Toutes les fonctionnalités', 'Accès à vie', 'Mises à jour incluses', 'Configuration premium', 'Support prioritaire', 'Offre limitée'],
  },
} as const;

export type MekLocPlanId = keyof typeof MEKLOC_PLANS;
export const MEKLOC_PLAN_LIST = [MEKLOC_PLANS.starter, MEKLOC_PLANS.pro, MEKLOC_PLANS.business, MEKLOC_PLANS.lifetime] as const;

export function getPlanRequestBilling(planId: MekLocPlanId) {
  return MEKLOC_PLANS[planId].billingChoice === 'six_months' ? '6-months' : MEKLOC_PLANS[planId].billingChoice === 'annual' ? '12-months' : 'lifetime';
}
